export enum NotificationType {
  USER = 'USER',
  COURSE = 'COURSE',
  GLOBAL = 'GLOBAL',
  ADMIN = 'ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  COURSE_REVIEWER = 'COURSE_REVIEWER',
  SUPPORT = 'SUPPORT',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
}

export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  COURSE_REVIEWER = 'COURSE_REVIEWER',
  SUPPORT = 'SUPPORT',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
}

export const ROLE_BASED_NOTIFICATION_TYPES = [
  NotificationType.ADMIN,
  NotificationType.INSTRUCTOR,
  NotificationType.COURSE_REVIEWER,
  NotificationType.SUPPORT,
  NotificationType.CONTENT_MANAGER,
  NotificationType.MARKETING_MANAGER,
];