export enum NotificationType {
  // Course notifications
  COURSE_CREATED = 'COURSE_CREATED',
  COURSE_UPDATED = 'COURSE_UPDATED',
  COURSE_PUBLISHED = 'COURSE_PUBLISHED',
  COURSE_REJECTED = 'COURSE_REJECTED',
  COURSE_REVIEW_REQUESTED = 'COURSE_REVIEW_REQUESTED',
  // Enrollment notifications
  ENROLLMENT_CREATED = 'ENROLLMENT_CREATED',
  // Support notifications
  SUPPORT_REQUEST_CREATED = 'SUPPORT_REQUEST_CREATED',
  // Promotion notifications
  PROMOTION_CREATED = 'PROMOTION_CREATED',
  PROMOTION_UPDATED = 'PROMOTION_UPDATED',
  PROMOTION_DELETED = 'PROMOTION_DELETED',
  PROMOTION_EXPIRED = 'PROMOTION_EXPIRED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  ARCHIVED = 'ARCHIVED',
}