export enum NotificationType {
  COURSE_CREATED = 'COURSE_CREATED',
  COURSE_UPDATED = 'COURSE_UPDATED',
  COURSE_PUBLISHED = 'COURSE_PUBLISHED',
  COURSE_REJECTED = 'COURSE_REJECTED',
  COURSE_REVIEW_REQUESTED = 'COURSE_REVIEW_REQUESTED',
  CHAT_SESSION_STARTED = 'CHAT_SESSION_STARTED',
  CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED',
  SUPPORT_AGENT_JOINED = 'SUPPORT_AGENT_JOINED',
  CHAT_SESSION_ENDED = 'CHAT_SESSION_ENDED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  ARCHIVED = 'ARCHIVED',
}