# Sử dụng Node.js làm base image
FROM node:18-alpine AS builder

# Thiết lập thư mục làm việc
WORKDIR /usr/src/app

# Copy file package.json và package-lock.json
COPY package.json package-lock.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Build ứng dụng Next.js
RUN npm run build

# Stage để chạy ứng dụng
FROM node:18-alpine

WORKDIR /usr/src/app

# Copy dependencies từ builder
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/.next ./.next

# Chạy Next.js ở chế độ production
CMD ["npm", "start"]
