export enum UserRole {
  ADMIN = 'ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  USER = 'USER',
  COURSEREVIEWER = 'COURSEREVIEWER',
  SUPPORT = 'SUPPORT',
  CONTENTMANAGER = 'CONTENTMANAGER',
  MARKETINGMANAGER = 'MARKETINGMANAGER',
}
